version: '3'
services:
  databasemysql:
    image: "mysql:latest"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=mediscreen
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    restart: always
    volumes:
      - db_data:/var/liv/mysql
    networks:
      - consumer-producer

  databasemongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - db_data:/var/liv/mongodb

  client:
    image: client
    build:
      context: ./client
      dockerfile: ./dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - diabetes
      - notes
      - patient
    networks:
      - consumer-producer

  diabetes:
    image: diabetes
    build:
      context: ./diabetes
      dockerfile: ./dockerfile
    ports:
      - "9003:9003"
    restart: always
    depends_on:
      - notes
      - patient
    networks:
      - consumer-producer

  notes:
    image: notes
    build:
      context: ./notes
      dockerfile: ./dockerfile
    ports:
      - "9002:9002"
    depends_on:
      - "databasemongodb"
    restart: always
    networks:
      - consumer-producer

  patient:
    image: patient
    build:
      context: ./patient
      dockerfile: ./dockerfile
    ports:
      - "9001:9001"
    depends_on:
      - "databasemysql"
    restart: always
    networks:
      - consumer-producer

volumes:
  db_data: {}

networks:
  consumer-producer: