version: '3'
services:
  databasemysql:
    image: "mysql:latest"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=mediscreen

  databasemongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD:

  client:
    image: client
    build:
      context: ./client
      dockerfile: ./dockerfile
    ports:
      - "8080:8080"

  diabetes:
    image: diabetes
    build:
      context: ./diabetes
      dockerfile: ./dockerfile
    ports:
      - "9003:9003"
    depends_on:
      - "databasemongodb"
      - "databasemysql"

  notes:
    image: notes
    build:
      context: ./notes
      dockerfile: ./dockerfile
    ports:
      - "9002:9002"
    depends_on:
      - "databasemongodb"

  patient:
    image: patient
    build:
      context: ./patient
      dockerfile: ./dockerfile
    ports:
      - "9001:9001"
    depends_on:
      - "databasemysql"

