#####FROM openjdk:8-jdk-alpine
#####VOLUME /tmp
#####ARG JAR_FILE = target/*.jar
#####COPY ${JAR_FILE} app.jar
#####ENTRY POINT ["java","-jar","/app.jar"]

#####EFROM openjdk:8-jdk-alpine
#####EVOLUME /tmp
#####EADD target/*.jar app.jar
#####EENV JAVA_OPTS=""
#####EENTRY POINT ["java","-jar","/app.jar"]


FROM openjdk:8-jdk-alpine
WORKDIR /app

COPY .mvn/ .mvn
COPY mvnw pom.xml ./
RUN ./mvnw dependency:resolve

COPY src ./src

CMD ["./mvnw", "spring-boot:run"]